import type { Project } from '@/types/content';

export const projects: Project[] = [
  {
    _id: '1',
    title: 'Busio',
    description:
      'A full-stack bus reservation system built with Node.js/Express backend and Nuxt.js frontend applications.',
    highlights: [
      'The system implements advanced seat availability algorithms, dynamic pricing based on seat priority, and comprehensive reservation management.',
    ],
    techStack: [
      'TypeScript',
      'React',
      'Next.js',
      'Tailwind CSS',
      'Node.js',
      'Express',
      'MongoDB',
    ],
    githubLink: 'https://github.com/serhatunver/bus-reservation',
    demoLink: '#',
    slug: 'bus-reservation-system',
  },
  {
    _id: '2',
    title: 'Project Two',
    description: 'This is the second project description.',
    highlights: ['Detailed information about Project Two.'],
    techStack: [
      'JavaScript',
      'Vue.js',
      'Nuxt.js',
      'Firebase',
      'CSS',
      'HTML',
      'Git',
      'Storybook',
    ],
    githubLink: '#',
    demoLink: '#',
    slug: 'project-two',
  },
  {
    _id: '3',
    title: 'Project Three',
    description: 'This is the second project description.',
    highlights: ['Detailed information about Project Two.'],
    techStack: [
      'JavaScript',
      'Vue.js',
      'Nuxt.js',
      'Firebase',
      'CSS',
      'HTML',
      'Git',
      'Storybook',
    ],
    githubLink: '#',
    demoLink: '#',
    slug: 'project-three',
  },
  {
    _id: '4',
    title: 'Project Four',
    description: 'This is the second project description.',
    highlights: ['Detailed information about Project Two.'],
    techStack: [
      'JavaScript',
      'Vue.js',
      'Nuxt.js',
      'Firebase',
      'CSS',
      'HTML',
      'Git',
      'Storybook',
    ],
    githubLink: '#',
    demoLink: '#',
    slug: 'project-four',
  },
  {
    _id: '5',
    title: 'Project Five',
    description: 'This is the second project description.',
    highlights: ['Detailed information about Project Two.'],
    techStack: [
      'JavaScript',
      'Vue.js',
      'Nuxt.js',
      'Firebase',
      'CSS',
      'HTML',
      'Git',
      'Storybook',
    ],
    githubLink: '#',
    demoLink: '#',
    slug: 'project-five',
  },
];
